"use client";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import React, { useEffect, useState } from "react";
import { HeaderMenu } from "./components/headerMenu/headerMenu";
import Footer from "./components/footer/footer";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [isTransparent, setIsTransparent] = useState(false);
  console.log("isTransparent", isTransparent);
  useEffect(() => {
    const handleScroll = () => {
      if (window.scrollY > 550) {
        // Ajustez le nombre de pixels selon vos besoins
        setIsTransparent(true);
      } else {
        setIsTransparent(false);
      }
    };

    window.addEventListener("scroll", handleScroll);

    return () => {
      window.removeEventListener("scroll", handleScroll);
    };
  }, []);

  const [toggleMenuIsOpen, setToggleMenuIsOpen] = React.useState(false);

  const handleOpenMenu = () => {
    setToggleMenuIsOpen(!toggleMenuIsOpen);
    console.log("toggleMenuIsOpen", toggleMenuIsOpen);
  };

  return (
    <>
      <html lang="en">
        <body className={inter.className}>
          <div
            className={`h-32 sticky top-0 z-10 flex items-center bg-zinc-50 phone:header phone:${
              isTransparent ? "transparent" : ""
            }`}
          >
            <HeaderMenu
              handleOpenMenu={handleOpenMenu}
              toggleMenuIsOpen={toggleMenuIsOpen}
            />
          </div>
          {children}
          <Footer />
        </body>
      </html>
    </>
  );
}
